apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard
spec:
  commonName: '*.example.com'
  dnsNames:
  - example.com # 원하는 도메인 입력
  - '*.example.com' # 원하는 도메인 입력
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: wildcard-tls